" Plugins

" Install vim-plug if it's not already installed
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()
" COC
Plug 'neoclide/coc.nvim', {'do': './install.sh nightly'}
Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-python', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-highlight', {'do': 'yarn install --frozen-lockfile'}
" End COC
Plug 'Galooshi/vim-import-js', { 'do': 'npm install -g import-js' }
Plug 'HerringtonDarkholme/yats.vim'
Plug 'Shougo/echodoc.vim'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'
Plug 'jeremyoverman/palenight.vim'
Plug 'heavenshell/vim-jsdoc'
Plug 'itchyny/calendar.vim'
Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'mxw/vim-jsx'
Plug 'pangloss/vim-javascript'
Plug 'scrooloose/nerdcommenter'
Plug 'scrooloose/nerdtree'
Plug 't9md/vim-choosewin'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'vimwiki/vimwiki'
Plug 'vim-scripts/auto-pairs-gentle'
Plug 'idanarye/vim-merginal'
Plug 'iamcco/markdown-preview.nvim', { 'do': 'cd app & yarn install'  }
call plug#end()

let mapleader = ","

filetype plugin indent on

" Functions
function Template(path)
    if line('$') == 1
        execute '0read' a:path
    endif
endfunction

" Hacks
inoremap <C-@> <C-x><C-o>

" Display
set noshowmode
set cmdheight=2
set showtabline=2

" Wrap
set nowrap

" Clipboard
set clipboard=unnamed

" Tabs
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent

" Tab Completion
set cot+=preview

inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"

" Colors
if (has("nvim"))
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

if (has("termguicolors"))
  set termguicolors
endif

let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
set background=dark
colorscheme palenight
let g:lightline = {
    \ 'colorscheme': 'palenight',
    \ 'separator': {'left': "", 'right': ''},
    \ 'subseparator': { 'left': '', 'right': ''},
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'gitbranch', 'cocstatus', 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'LightlineFugitive',
    \   'cocstatus': 'coc#status'
    \ }
    \ }

function! LightlineFugitive()
    if exists('*fugitive#head')
        let branch = fugitive#head()
        return branch !=# '' ? ' '.branch : ''
    endif
    return ''
endfunction

syntax on

" Movement
nnoremap j gj
nnoremap k gk

" Gutters
set number
set updatetime=100
set signcolumn=yes
map <silent> <Leader>l :set relativenumber!<Cr>

" Window management
set splitbelow
set splitright
set noea

map <Left> <C-w>2<
map <Right> <C-w>2>
map <Up> <C-w>+
map <Down> <C-w>-

nmap <Leader>v <Plug>(choosewin)
let g:choosewin_overlay_enable = 1

" NERDTree Confirguration
let g:NERDTreeNodeDelimiter = "\u00a0"
map <Leader>f :NERDTreeToggle<Enter>

" VimWiki
autocmd BufEnter diary.wiki VimwikiDiaryGenerateLinks
autocmd FileType calendar nmap <buffer> <CR> :call vimwiki#diary#calendar_action(b:calendar.day().get_day(), b:calendar.day().get_month(), b:calendar.day().get_year(), b:calendar.day().week(), "V")<CR>
map <Leader>w/ :VimwikiSearch /\c

let g:javascript_plugin_jsdoc = 1

" Search
set ignorecase
set smartcase
map <Leader>s :Ag 

" Directories
set undofile
set backup

set directory=$HOME/.vim/swapfiles//
set backupdir=$HOME/.vim/backups//
set undodir=$HOME/.vim/undodir//

" Git stuff
nnoremap <Leader>b :MerginalToggle<cr>
nnoremap <Leader>gs :Gstatus<cr>
nnoremap <Leader>gc :Gcommit<cr>
nnoremap <Leader>gp :Gpush<cr>
nnoremap <Leader>gw :Gwrite<cr>

" Markdown
let g:mkdp_auto_start=0
let g:mkdp_auto_close=0
